### ISSUE TITLE
UI - Search option 

### ISSUE THREAD

**Issue by rashmisandilya** [moharnab123saikia/CSC510-group-f#15]

**Comment by pranjaldeka** [comment]
@rashmisandilya  Can this be closed ?

**Comment by rashmisandilya** [comment]
The list of restaurants is not that big so and this is added legacy.. For now focussing more on functionality.. So closing this

**Comment by rashmisandilya** [comment]
Adding this to March work. Beautification and enhancement for better user experience

**Comment by rashmisandilya** [comment]
No need for this
