### ISSUE TITLE
Frame the JSON format to store the ratings and reviews

### ISSUE THREAD

**Issue by sbalakr2** [moharnab123saikia/CSC510-group-f#17]

**Comment by sbalakr2** [comment]
[sample_json.txt](https://github.com/moharnab123saikia/CSC510-group-f/files/136803/sample_json.txt)

**Comment by sbalakr2** [comment]
I have shared the sample JSON for saving the reviews. Could you all please check it once and let me know if anything else has to be added?

**Comment by sbalakr2** [comment]
{"restaurants" :[
    {
        "restaurant_id_1" : {
                            "name" : "el cerro",
                            "data" : {
                                        "yelp" : {
                                            "rating" : "4.5",
                                            "count" : "45",
                                            "reviews" : ["test", "tst2"]
                                        },
                                        "googleratings" : {
                                            "rating" : "5",
                                            "count" : "34",
                                            "reviews" : ["sample"]
                                        },
                                        "tripadvisor" : {
                                            "rating" : "",
                                            "count" : "",
                                            "reviews" : ["test", "test2"]
                                        }
                                }
                        }
    }, 
    {
        "restaurant_id_2" : {
                            "name" : "ruckus",
                            "data" : {
                                        "yelp" : {
                                            "rating" : "5",
                                            "count" : "23",
                                            "reviews" : ["sample"]
                                        },
                                        "googleratings" : {
                                            "rating" : "4.7",
                                            "count" : "56",
                                            "reviews" : ["sample2"]
                                        },
                                        "tripadvisor" : {
                                            "rating" : "4.6",
                                            "count" : "27",
                                            "reviews" : ["test"]
                                        }
                                }
                        }
    }
    ]}

**Comment by moharnab123saikia** [comment]
Is the review scale not needed?

**Comment by sbalakr2** [comment]
Yes, you are right. I will update the JSON.

**Comment by sbalakr2** [comment]
"reviews" : [{
    "scale" : "4",
    "review" : "test"
},{
    "scale" : "4.2",
    "review" : "test1"
}]

Modified the value for the reviews.

**Comment by sbalakr2** [comment]
Will this be okay?
