### ISSUE TITLE
Designing the app interface

### ISSUE THREAD

**Issue by sbalakr2** [moharnab123saikia/CSC510-group-f#22]

**Comment by moharnab123saikia** [comment]
Are we using lollipop or any latest API like marshmallow

**Comment by rashmisandilya** [comment]
We willl be designing for kitkat now. It will work for all with a  minor change in menifest.xml.

**Comment by rashmisandilya** [comment]
As of now designed for Android 5.0 (lollipop)- minimum  sdk version required is 21
