### ISSUE TITLE
Collecting log for the web scraper solution

### ISSUE THREAD

**Issue by sbalakr2** [moharnab123saikia/CSC510-group-f#58]
Collecting the telemetry feedback from the users on the usage the the web application that aggregates the restaurant reviews.

**Comment by pranjaldeka** [comment]
we will be using this survey for telemetry purpose https://docs.google.com/forms/u/0/d/1JJj4uUI6TubhzHoF6ydFe7us__1kgEDo7gDa03Y4riE/viewform?ntd=1&ths=true&edit_requested=true&pli=1#password

**Comment by rashmisandilya** [comment]
Google Analytics data for pulling the log for  the web scrapper website.
