### ISSUE TITLE
Log tracking addition to plugin

### ISSUE THREAD

**Issue by pranjaldeka** [moharnab123saikia/CSC510-group-f#59]

**Comment by sbalakr2** [comment]
We should track the type of browser users are using which will help us to understand the requirements.

**Comment by rashmisandilya** [comment]
[Google Analytics for browser](https://analytics.google.com/analytics/web/?authuser=0#report/visitors-browser/a74501177w112681598p117712609/)

**Comment by rashmisandilya** [comment]
Done
