### ISSUE TITLE
Telemetry and log for android app

### ISSUE THREAD

**Issue by rashmisandilya** [moharnab123saikia/CSC510-group-f#60]
Logs generated by us, thrashing around the mobile tool, to show data from users could be collected this way.

**Comment by sbalakr2** [comment]
We can get the logs of user surveys in the mobile from the users of the android app and understand how the app is used and what features can be improved/added.

**Comment by rashmisandilya** [comment]
Google analytics is another way out for data log.

**Comment by sbalakr2** [comment]
Yes that would be great, we just need to check the feasibility.

**Comment by rashmisandilya** [comment]
Sample log file for this issue and google analytic link uploaded. closing!!!!
