### ISSUE TITLE
Design the UI - creating and styling the web page

### ISSUE THREAD

**Issue by sbalakr2** [moharnab123saikia/CSC510-group-f#7]

**Comment by pranjaldeka** [comment]
@moharnab123saikia  Please add a background image and make some UI changes like displaying individual reviews

**Comment by rashmisandilya** [comment]
Isn't this done?

**Comment by pranjaldeka** [comment]
Some minor UI editing is left (like background image, individual reviews). @moharnab123saikia  will be working on this tomorrow.

**Comment by rashmisandilya** [comment]
@moharnab123saikia done, right?

**Comment by pranjaldeka** [comment]
https://github.com/moharnab123saikia/CSC510-group-f/commit/174f38dd67d1e35d4502f0ff0e534050c4b6d170
